fix command option completion
lambdalisue/fern.vim pull request #242
Opened 2020-10-06 13:30 UTC by Milly

- Remove deprecated command completion.
- Add completion for `:FernDo` and `:FernReveal`.
- Fix completion pattern matching.
- Add tests.

2020-10-06 16:00 UTC, lambdalisue requested changes
Thanks for your contribution 👍 
I just requested a small change so please check it.

2020-10-07 00:05 UTC, lambdalisue requested changes
One more

2020-10-07 00:05 UTC, lambdalisue commented on autoload/fern/internal/complete.vim
> +  let pattern = escape(a:arglead, s:ESCAPE_PATTERN)
The leading `^` is required.

```suggestion
  let pattern = '^' . escape(a:arglead, s:ESCAPE_PATTERN)
```

2020-10-07 00:05 UTC, lambdalisue commented on autoload/fern/internal/complete.vim
> +  let pattern = escape(a:arglead, s:ESCAPE_PATTERN)
Same

```suggestion
  let pattern = '^' . escape(a:arglead, s:ESCAPE_PATTERN)
```

2020-10-07 01:48 UTC, Milly commented
- Added tests for invalid patterns.

2020-10-07 03:55 UTC, lambdalisue approved these changes
LGTM

2020-10-07 03:55 UTC, merged

2020-10-07 03:56 UTC, lambdalisue commented
Thanks a lot. Released as https://github.com/lambdalisue/fern.vim/releases/tag/v1.26.5