Add `g:fern#sync_removes_to_buffer` and `g:fern#sync_renames_to_buffer`
lambdalisue/fern.vim pull request #248
Opened 2020-10-14 03:00 UTC by hrsh7th

Hi, Thank you for the great work.

I want to prevent to synchronize file remove operations so I create an option for it.

2020-10-14 03:56 UTC, lambdalisue requested changes

2020-10-14 03:56 UTC, lambdalisue commented on autoload/fern.vim
> +      \ 'sync_removes_to_buffer': v:true,
Please rename it and use `0/1`  as ordinal like:

```suggestion
      \ 'disable_renamer_buffer_delete': 0,
```

2020-10-14 03:56 UTC, lambdalisue commented on autoload/fern.vim
> +      \ 'sync_renames_to_buffer': v:true,
Please rename it and use `0/1`  as ordinal like:

```suggestion
      \ 'disable_renamer_buffer_rename': 0,
```

2020-10-14 04:17 UTC, hrsh7th commented on autoload/fern.vim
> +      \ 'sync_removes_to_buffer': v:true,
すいません。こちら、`disable_renamer` は `disable_remover` の間違いとかではなさそうでしょうか？

名前については自信あんまりなかったので、ご指摘助かります。

2020-10-14 04:19 UTC, hrsh7th commented on autoload/fern.vim
> +      \ 'sync_removes_to_buffer': v:true,
ちなみに、自分としては「名前変更は追従してほしいけど、バッファが消えるのは辛かった」というのが根本的な欲求でした。
その上で、本機能追加ではない方法で対応できそうである場合は close してもらっても大丈夫です！

2020-10-14 06:05 UTC, lambdalisue commented on autoload/fern.vim
> +      \ 'sync_removes_to_buffer': v:true,
> すいません。こちら、disable_renamer は disable_remover の間違いとかではなさそうでしょうか？

たしかに。代替として

- `disable_auto_buffer_delete`
- `disable_auto_buffer_rename`

でお願いします :bow:

2020-10-14 06:14 UTC, hrsh7th commented on autoload/fern.vim
> +      \ 'sync_removes_to_buffer': v:true,
了解しましたー！

2020-10-14 10:10 UTC, hrsh7th commented
ご指摘事項を反映しておきました！

2020-10-15 02:23 UTC, lambdalisue requested changes

2020-10-15 02:23 UTC, lambdalisue commented on autoload/fern/internal/buffer.vim
> +  if g:fern#disable_auto_buffer_delete
確かにこの関数内でチェックするのが簡単ですが、副作用はなるべく外側に出したいので呼び出し側でチェックする様にお願いします。

2020-10-15 02:34 UTC, hrsh7th commented on autoload/fern/internal/buffer.vim
> +  if g:fern#disable_auto_buffer_delete
了解しました。

2020-10-20 15:55 UTC, lambdalisue approved these changes
LGTM

2020-10-20 15:56 UTC, merged