Add new focus:parent action
lambdalisue/fern.vim pull request #316
Opened 2021-03-23 14:42 UTC by shanesmith

Could easily be a plugin but it felt like it might belong here.

The action is style as `focus:x` for any future actions that might also set the focus.

A default mapping of `p` is added.

2021-03-24 03:46 UTC, lambdalisue requested changes
Thanks for the contribution! Please remove the default mapping and add documentation for that mapping in `docs/fern.txt` 👍

2021-03-24 03:46 UTC, lambdalisue commented on autoload/fern/mapping/node.vim
> +    nmap <buffer><nowait> p <Plug>(fern-action-focus:parent)
Please remove this. Let users to define the mapping for that.

2021-03-24 13:52 UTC, shanesmith commented
The docs of course, my bad! I've also removed the mapping.

2021-03-25 04:31 UTC, lambdalisue approved these changes
LGTM

2021-03-25 04:31 UTC, merged

2021-03-25 04:32 UTC, lambdalisue commented
Merged and released as v1.34.0 👍  Thanks for the contribution 🎉

2021-03-25 13:06 UTC, shanesmith commented
Much appreciated!