feat: add support for rendering text with props
lambdalisue/fern.vim pull request #465
Opened 2023-02-14 20:05 UTC by brandon1024

Introduce the ability to render text with attached text properties. Renderers may now return list of dictionaries where each line of text can include text properties for additional text styling capabilities. This change is backwards compatible with existing renderers; they will continue to work as before.

The semantics of this feature was inspired by popup_create(), which can accept a list of dictionaries with a 'text' and 'props' key.

This feature enhances the capabilities of custom renderers. In particular, it's possible to implement renderers that render content with dynamically-defined style. The screenshot below shows a simple custom renderer that renders vim files in orange, other files in grey and directories in blue.

![image](https://user-images.githubusercontent.com/22732449/218848935-611021ce-47ab-4bc3-a776-f14bdc7cc14c.png)

2023-02-20 07:10 UTC, lambdalisue reviewed
Not sure but does this work on Neovim as well?

2023-02-21 00:23 UTC, brandon1024 commented
@lambdalisue I don't believe so. From what I've read, [extmarks](https://neovim.io/doc/user/api.html#extmarks) is the neovim-equivalent to textprops but they are not compatible. [This issue](https://github.com/neovim/neovim/issues/13661) describes why textprops weren't introduced in neovim.

I guess the next question is where we go from here :sweat_smile: We might be able to build a shim that uses textprops for vim and extmarks for neovim, so that these features can be used for both editors. Alternatively we could document that textprops are only supported in vim. What are your thoughts? I'd love to support both but I have literally no experience with Neovim, so I'd need some guidance. Documenting that textprops are only supported for Vim seems the easiest to me.

2023-02-21 06:21 UTC, lambdalisue commented
> Alternatively we could document that textprops are only supported in vim

It sounds reasonable enough. It's OK if this change does not break current features in Neovim (I guess the current code breaks features on Neovim, right?)

2023-02-21 12:40 UTC, brandon1024 commented
> It sounds reasonable enough.

Cool, this makes my life easier. I'm sure someone will be interested in implementing this for extmarks at some point too.

> It's OK if this change does not break current features in Neovim (I guess the current code breaks features on Neovim, right?)

Existing renderers should continue to work as before, for both vim and neovim :smiley:  The [changes I've introduced](https://github.com/lambdalisue/fern.vim/pull/465/files#diff-50c56ae0ae12ca3441013c63534702db02e4a3dcf02d888f3257ff131aecdc1bR18) check to see if it was passed a list of strings or a list of dictionaries. If passed dictionaries, it would fail, but that would be user error. I can also add a check to see if we are in vim or neovim and throw a useful error message too, or log a message. I might do that actually, not a bad idea.

2023-02-22 14:11 UTC, brandon1024 commented
I've adjusted the docs, indicating that text properties are only supported in vim. I also added a check and a useful error message when trying to render text properties in neovim.

I guess the next question for you @lambdalisue , would you prefer that we fail abruptly if trying to use text properties in neovim, or just skip the text properties and render a plain-text tree? In code:

```vim
    if !empty(props) && !exists('*prop_add')
      throw 'text properties are not supported, prop_add() does not exist.'
    endif

    for prop in props
      let prop.bufnr = a:bufnr
      call prop_add(lnum + 1, prop.col, prop)
    endfor
```

or

```vim
    if exists('*prop_add')
      for prop in props
        let prop.bufnr = a:bufnr
        call prop_add(lnum + 1, prop.col, prop)
      endfor
    endif
```

I've thought about it a bit, I think the second one makes more sense, since we'd still render a file tree but it just wouldn't be colorized.

2023-02-24 02:56 UTC, lambdalisue commented
> or just skip the text properties and render a plain-text tree

Seems nice. 

Additionally, I just moved so I need to find time to check PRs so please be patient. I'm sorry for that.

2023-02-24 03:18 UTC, brandon1024 commented
No worries :-)

2023-02-24 12:30 UTC, brandon1024 commented
@lambdalisue I think this is ready to go now, whenever you get a second :-)

2023-03-01 14:21 UTC, lambdalisue requested changes

2023-03-01 14:21 UTC, lambdalisue commented on autoload/fern/internal/buffer.vim
> +  endfor
The use of for loops in Vim scripts has a significant impact on performance, so this part of the script should be optionally controllable.

2023-03-10 14:00 UTC, brandon1024 commented on autoload/fern/internal/drawer/hover_popup.vim
> -    syntax clear FernRoot
I'm pretty sure this is a bug. It was giving me some trouble so I fixed it here :-)

2023-03-10 18:52 UTC, lambdalisue approved these changes
LGTM

2023-03-10 18:52 UTC, merged

2023-03-10 18:52 UTC, lambdalisue commented
Thanks for your contribution 👍

2023-03-10 19:00 UTC, brandon1024 commented
Thanks @lambdalisue :-)